spring:
  redis:
    host: 192.168.1.213
    port: 6379
    password: 123456789
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.212:3306/bq_operational_analysis?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: BQpa55d-#
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  mvc:
    servlet:
      load-on-startup: 1
# aop配置
  aop:
    auto: true
    proxy-target-class: true
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#    sender:
#      type: web
access_token:
  store-jwt: false
logging:
  level:
    root: info
    com.bqhx.officeautomation: debug
  file: E:/logs/oauth-center/${spring.application.name}.log
security:
  oauth2:
    resource:
      filter-order: 3
    client:
          access-token-validity-seconds: 28800
          refresh-token-validity-seconds: 28800
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eager-load:
    enabled: true
    clients: user-center
